@echo off
echo Cleaning...
:: Compiler-generated binaries
for /f "delims=" %%a in ('dir /B /S *.exe, *.dll, *.bpl, *.bpi, *.dcp, *.so, *.apk, *.drc, *.map, *.dres, *.rsm, *.tds, *.dcu, *.lib, *.a, *.o, *.ocx, *.res  2^>nul') do del "%%a"

:: Autogenerated files
for /r . %%i in (*.cfg) do if not "%%~nxi"=="mms.cfg" del /f /q "%%i"
for /f "delims=" %%a in ('dir /B /S *.hpp, *Resource.rc  2^>nul') do del "%%a"

:: Local files
for /f "delims=" %%a in ('dir /B /S *.local, *.identcache, *.projdata, *.tvsconfig, *.dsk  2^>nul') do del "%%a"

:: Others
for /f "delims=" %%a in ('dir /B /S *.~*, *.stat  2^>nul') do if exist "%%a" del /f /q "%%a"
for /f "delims=" %%a in ('dir /B /S _LOG_.txt, dunit.ini, VersionInfo.res  2^>nul') do del "%%a"

for /d /r . %%d in ("__history")  do @if exist "%%d" rd /s /q "%%d"
for /d /r . %%d in ("__recovery") do @if exist "%%d" rd /s /q "%%d"
for /d /r . %%d in ("modules") do @if exist "%%d" rd /s /q "%%d"
for /d /r . %%d in ("Dcu") do @if exist "%%d" rd /s /q "%%d"
for /d /r . %%d in ("Release") do @if exist "%%d" rd /s /q "%%d"
for /d /r . %%d in ("Debug") do @if exist "%%d" rd /s /q "%%d"
for /d /r . %%d in ("Compiled") do @if exist "%%d" rd /s /q "%%d"