VER_Major     = 3;
VER_Minor     = 9;
VER_Build     = 21;
VER_Revision  = 0;
VER_Sufix     = '-port';

(* Version control
VER_CompanyName      = 'BerSoft';
VER_FileDescription  = 'Era Project';
VER_InternalName     = '';
VER_LegalCopyright   = '(C) Berserker aka EtherniDee aka BerSoft';
VER_LegalTrademarks  = '';
VER_OriginalFilename = 'era.dll';
VER_ProductName      = 'Era';
VER_Comments         = '';
*)